#!/bin/bash

# Setup script for meal notification cron job
# This script helps configure the cron job on your VPS

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get the current directory (project root)
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CRON_SCRIPT="$PROJECT_DIR/scripts/cron-runner.js"

echo -e "${BLUE}🚀 Setting up meal notification cron job...${NC}"
echo -e "${BLUE}📁 Project directory: $PROJECT_DIR${NC}"

# Check if Node.js is installed
if ! command -v node &> /dev/null; then
    echo -e "${RED}❌ Node.js is not installed. Please install Node.js first.${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Node.js found: $(node --version)${NC}"

# Make the cron runner executable
chmod +x "$CRON_SCRIPT"
echo -e "${GREEN}✅ Made cron runner executable${NC}"

# Check if .env.local exists
if [ ! -f "$PROJECT_DIR/.env.local" ]; then
    echo -e "${YELLOW}⚠️  .env.local not found. Make sure to set environment variables.${NC}"
else
    echo -e "${GREEN}✅ Environment file found${NC}"
fi

# Create a wrapper script that loads environment variables
WRAPPER_SCRIPT="$PROJECT_DIR/scripts/cron-wrapper.sh"
cat > "$WRAPPER_SCRIPT" << EOF
#!/bin/bash

# Cron wrapper script that loads environment variables
# Generated by setup-cron.sh

cd "$PROJECT_DIR"

# Load environment variables from .env.local if it exists
if [ -f ".env.local" ]; then
    export \$(grep -v '^#' .env.local | xargs)
fi

# Run the cron job
exec node scripts/cron-runner.js
EOF

chmod +x "$WRAPPER_SCRIPT"
echo -e "${GREEN}✅ Created cron wrapper script${NC}"

# Generate crontab entry
CRON_ENTRY="0 * * * * $WRAPPER_SCRIPT >> $PROJECT_DIR/logs/cron.log 2>&1"

echo -e "\n${YELLOW}📋 Cron job configuration:${NC}"
echo -e "${BLUE}   Schedule: Every hour (0 * * * *)${NC}"
echo -e "${BLUE}   Script: $WRAPPER_SCRIPT${NC}"
echo -e "${BLUE}   Logs: $PROJECT_DIR/logs/cron.log${NC}"

# Create logs directory
mkdir -p "$PROJECT_DIR/logs"
echo -e "${GREEN}✅ Created logs directory${NC}"

# Show current crontab
echo -e "\n${YELLOW}📋 Current crontab:${NC}"
crontab -l 2>/dev/null || echo "No crontab found"

echo -e "\n${YELLOW}🔧 To install the cron job, run:${NC}"
echo -e "${BLUE}   (crontab -l 2>/dev/null; echo \"$CRON_ENTRY\") | crontab -${NC}"

echo -e "\n${YELLOW}🔧 To remove the cron job later, run:${NC}"
echo -e "${BLUE}   crontab -l | grep -v \"cron-wrapper.sh\" | crontab -${NC}"

echo -e "\n${YELLOW}🧪 To test the cron job manually, run:${NC}"
echo -e "${BLUE}   cd $PROJECT_DIR && $WRAPPER_SCRIPT${NC}"

echo -e "\n${YELLOW}📊 To view cron logs, run:${NC}"
echo -e "${BLUE}   tail -f $PROJECT_DIR/logs/cron.log${NC}"

echo -e "\n${GREEN}✅ Setup complete!${NC}"

# Ask if user wants to install the cron job now
read -p "Do you want to install the cron job now? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo -e "${BLUE}📝 Installing cron job...${NC}"
    (crontab -l 2>/dev/null; echo "$CRON_ENTRY") | crontab -
    echo -e "${GREEN}✅ Cron job installed successfully!${NC}"
    
    echo -e "\n${YELLOW}📋 Updated crontab:${NC}"
    crontab -l
else
    echo -e "${YELLOW}⏭️  Skipped cron job installation. You can install it manually later.${NC}"
fi

echo -e "\n${BLUE}🎉 All done! Your meal notification system is ready.${NC}"